In [1]:
import torch
from torch import hub


In [2]:
import torchvision

In [3]:
img_t = torch.randn(3, 5, 5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [4]:
batch_t = torch.randn(2, 3, 5, 5)

In [5]:
"""
バッチ次元の有無により
RGBのチャネルは0か1のため
終わりから数えると-3にRGBがくる
"""

'\nバッチ次元の有無により\nRGBのチャネルは0か1のため\n終わりから数えると-3にRGBがくる\n'

In [6]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)

img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [22]:
#重みを1次元から3次元へ[3,1,1]
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
#broadcastingされてimgには「3、5、5」としてbacthには「2,3,5,5」となり次元が追加される
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)

img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
print(weights.shape)
print(unsqueezed_weights.shape, img_t.shape ,img_weights.shape, img_gray_weighted.shape) 
print(unsqueezed_weights.shape, batch_t.shape, batch_weights.shape, batch_gray_weighted.shape) 

torch.Size([3])
torch.Size([3, 1, 1]) torch.Size([3, 5, 5]) torch.Size([3, 5, 5]) torch.Size([5, 5])
torch.Size([3, 1, 1]) torch.Size([2, 3, 5, 5]) torch.Size([2, 3, 5, 5]) torch.Size([2, 5, 5])


In [23]:
img_t[1][1],img_weights[1][1],unsqueezed_weights[1]

(tensor([-0.3908,  0.9805,  0.3786, -0.5636, -1.2243]),
 tensor([-0.2795,  0.7012,  0.2708, -0.4031, -0.8756]),
 tensor([[0.7152]]))

In [30]:
#数値型
#必要に応じて低ビットを使う

In [38]:
double_points = torch.ones(10, 2 ,dtype=torch.double)#64倍制度浮動小数点
short_points = torch.tensor([[1,2], [3,4]], dtype=torch.short)#short=16符号付き整数
bit_points = torch.zeros(3,3, dtype=torch.int)

In [39]:
double_points.dtype

torch.float64

In [40]:
short_points.dtype

torch.int16

In [41]:
bit_points.dtype

torch.int32

In [43]:
#キャスト機能も使える
moto=torch.zeros(10, 2)
henka=moto.short()
moto.dtype, henka.dtype 

(torch.float32, torch.int16)

In [47]:
#関数でもいける
anather_use = henka.to(torch.double)
anather_use.dtype

torch.float64