In [1]:
import torch
from torch import hub


In [2]:
import torchvision

In [3]:
img_t = torch.randn(3, 5, 5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [4]:
batch_t = torch.randn(2, 3, 5, 5)

In [5]:
"""
バッチ次元の有無により
RGBのチャネルは0か1のため
終わりから数えると-3にRGBがくる
"""

'\nバッチ次元の有無により\nRGBのチャネルは0か1のため\n終わりから数えると-3にRGBがくる\n'

In [6]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)

img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [22]:
#重みを1次元から3次元へ[3,1,1]
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
#broadcastingされてimgには「3、5、5」としてbacthには「2,3,5,5」となり次元が追加される
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)

img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
print(weights.shape)
print(unsqueezed_weights.shape, img_t.shape ,img_weights.shape, img_gray_weighted.shape) 
print(unsqueezed_weights.shape, batch_t.shape, batch_weights.shape, batch_gray_weighted.shape) 

torch.Size([3])
torch.Size([3, 1, 1]) torch.Size([3, 5, 5]) torch.Size([3, 5, 5]) torch.Size([5, 5])
torch.Size([3, 1, 1]) torch.Size([2, 3, 5, 5]) torch.Size([2, 3, 5, 5]) torch.Size([2, 5, 5])


In [23]:
img_t[1][1],img_weights[1][1],unsqueezed_weights[1]

(tensor([-0.3908,  0.9805,  0.3786, -0.5636, -1.2243]),
 tensor([-0.2795,  0.7012,  0.2708, -0.4031, -0.8756]),
 tensor([[0.7152]]))

In [30]:
#数値型
#必要に応じて低ビットを使う

In [38]:
double_points = torch.ones(10, 2 ,dtype=torch.double)#64倍制度浮動小数点
short_points = torch.tensor([[1,2], [3,4]], dtype=torch.short)#short=16符号付き整数
bit_points = torch.zeros(3,3, dtype=torch.int)

In [39]:
double_points.dtype

torch.float64

In [40]:
short_points.dtype

torch.int16

In [41]:
bit_points.dtype

torch.int32

In [43]:
#キャスト機能も使える
moto=torch.zeros(10, 2)
henka=moto.short()
moto.dtype, henka.dtype 

(torch.float32, torch.int16)

In [47]:
#関数でもいける
anather_use = henka.to(torch.double)
anather_use.dtype

torch.float64

In [49]:
#テンソルの演算
#テンソルの演算はほとんどtorchモジュールで可能
#http://pytorch.org/docs



In [58]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
#次元の交換
print(a.shape, a_t.shape)

torch.Size([3, 2]) torch.Size([2, 3])


In [60]:
a_t = a.transpose(0,1)
print(a_t.shape)

torch.Size([2, 3])


In [61]:
#テンソルとストレージの表示関係

In [84]:
big_points=torch.zeros(6,4,2)
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_points = points[1]

In [85]:
second_points

tensor([5., 3.])

In [86]:
print(points.size())
print(second_points.size(), second_points.shape)
print(big_points.shape)

torch.Size([3, 2])
torch.Size([2]) torch.Size([2])
torch.Size([6, 4, 2])


In [107]:
#オフセット

#横に並べて、最初の要素からいくつ目か
#points[2]は二つの要素の点をスキップしないといけない
#pointsはそれ自身しかない
print(points[1].storage_offset(), points.storage_offset(),)
print(big_points.storage_offset(), big_points[1,1,0].storage_offset())

2 0
0 10


In [108]:
#ストライド

#各インデックスを増加した時スキップしないといけない要素数
#各次元の要素数ー1
points.stride(), second_points.stride(), 

((2, 1), (1,))

In [121]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_points = points[1]
second_points

tensor([5., 3.])

In [122]:
second_points[1]=10.0

In [123]:
points

tensor([[ 4.,  1.],
        [ 5., 10.],
        [ 2.,  1.]])

In [124]:
#サブテンソルの変更は元のテンソルへも影響がある
#影響を避けるにはclone()

second_points = points[1].clone()
second_points

tensor([ 5., 10.])

In [125]:
second_points[1] =200
points

tensor([[ 4.,  1.],
        [ 5., 10.],
        [ 2.,  1.]])

In [127]:
#天地
points, points.t()

(tensor([[ 4.,  1.],
         [ 5., 10.],
         [ 2.,  1.]]),
 tensor([[ 4.,  5.,  2.],
         [ 1., 10.,  1.]]))

In [128]:
#高次元での天地は二次元を指定する

some_t = torch.ones(3,4,5)
transpose_some_t = some_t.transpose(0,2)
print(some_t.shape, transpose_some_t.shape)

torch.Size([3, 4, 5]) torch.Size([5, 4, 3])


In [133]:
#要素が連続しているか確認
points.shape, points.is_contiguous()

(torch.Size([3, 2]), True)

In [137]:
#天地した行列は連続していない
points.t().shape, points.t().is_contiguous()

(torch.Size([2, 3]), False)

In [138]:
points_t = points.t()
points_t_cont = points_t.contiguous()

In [139]:
#contiguous()で新しいテンソルが作られる
points_t_cont.is_contiguous()

True

In [ ]:
#GPUへの転送
